#!/bin/bash
#source /etc/default/tools
red='\e[0;31m'
blue='\e[0;34m'
green='\e[0;32m'
yellow='\e[1;33m'
white='\e[1;37m'
#include file
source ./func.sh

main () {
clear
DIALOG=${DIALOG=dialog}
tempfile=`tempfile 2>/dev/null` || tempfile=/tmp/test$$

$DIALOG --backtitle "$title" \
        --clear --title "$version" \
        --menu "Please select the option :" 20 51 20 \
        "1"  "Install Docker " \
        "2"  "TO DO" \
        "3"  "TO DO" \
        "4"  "TO DO" \
        "5"  "Exit" 2> $tempfile

input=`cat $tempfile`

case "$input" in
1)
Install_Docker
;;
2)
fun_Advance_Configuration
;;
3)
fun_ibsng
;;
4)
fun_enable_service
;;

5)
exit 0
;;
esac
}
main
